---
title: "bird baths"
author: "Joshua Allen"
date: "8/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load("tidyverse", "janitor", "ggridges", "ggalt","ggalluvial")

devtools::install_github(repo = "shandiya/feathers", ref = "main")

bird_raw = tidytuesdayR::tt_load(2021, week = 36)

bird_baths = bird_raw$bird_baths



```




```{r}
if(!require("showtext")) {
	print("Install the package `showtext`.")
} else {
	library("showtext")
	showtext_auto()
	font_add_google("Fira Sans", "fira_sans")
	font_add_google("Merriweather", "merriweather")
}


theme_allen = function(title_pos = "center", axis_title_pos = "left", 
                       slides = FALSE, has_subtitle = FALSE, 
                       base_size = 14, ...){
  
  title_hjust <- switch(title_pos, "center" = 0.5, "left" = 0)
  axis_title_hjust_y <- switch(axis_title_pos, "center" = 0.5, "left" = 1.0)
  axis_title_hjust_x <- switch(axis_title_pos, "center" = 0.5, "left" = 0.0)
  plot_bg = if_else(slides, "#ECECEC", "transparent")
  plot_grid = if_else(slides, "grey85", "grey92")
  title_margin = if_else(has_subtitle, "4", "16")
  
  
  theme_bw(base_family = "fira_sans", 
                base_size = base_size)  +
    theme(plot.title = ggplot2::element_text(
      # Font
      family = "merriweather", face = "bold", size = rel(1.285), 
      colour = "#454545", 
      # Center title
      hjust = title_hjust,
      # Margins
      margin = ggplot2::margin(b = title_margin, unit = "pt")
    ),
    plot.subtitle = ggplot2::element_text(
      # Font
      family = "merriweather", face = "italic", size = rel(.86), 
      colour = "#454545", 
      # Center subtitle 
      hjust = title_hjust,
      # Margins
      margin = ggplot2::margin(b = 16, unit = "pt")
    ),
    plot.title.position = "plot",
    
    ## Caption -------------------------------------------------------------
    plot.caption = ggplot2::element_text(
      # Font
      size = rel(0.72), colour = "#454545",
      # Right-align caption
      hjust = 1,
      # Margins
      margin = ggplot2::margin(t = 20)
    ),
    plot.caption.position = "plot",
    
    ## Axis ----------------------------------------------------------------
    # Axis title
    axis.title = ggplot2::element_text(
      # Font
      size = rel(.86), colour = "#454545", face = "italic"
    ),
    # Axis Title x/y
    axis.title.y = ggplot2::element_text(
      # Right-align y axis title
      hjust = axis_title_hjust_y,
      # Margins
      margin = ggplot2::margin(r = 10)
    ),
    axis.title.x = ggplot2::element_text(
      # Left-align x axis title
      hjust = axis_title_hjust_x,
      # Margins
      margin = ggplot2::margin(t = 10)
    ),
    # Axis labels
    axis.text = ggplot2::element_text(
      # Font
      size = rel(.72), colour = "#212121"
    ),
    # Axis Lines
    axis.line = element_line(
      colour = "grey40"
    ),
    panel.grid = element_line(
      colour = plot_grid
    ),
    
    
    ## Legend -------------------------------------------------------------
    # Legend title
    legend.title = ggplot2::element_text(
      # Font
      size = rel(.86), colour = "#454545"
    ),
    # Legend labels
    legend.text = ggplot2::element_text(
      # Font
      size = rel(.72), colour = "#454545"
    ),
    legend.background = ggplot2::element_rect(
      # No Background Colour
      fill = "transparent", colour = NA
    ),
    legend.key = ggplot2::element_rect(
      # No Background Colour
      fill = "transparent", colour = NA
    ),
    
    
    ## Facet Wrap ----------------------------------------------------------
    strip.text = ggplot2::element_text(
      # Font 
      size = rel(.86), colour = "#454545", 
      # Margin							   
      margin = ggplot2::margin(t= 10, b= 10)
    ),
    strip.background = ggplot2::element_rect(
      # No Background Colour
      fill = "transparent", colour = NA
    ),
    
    ## Panel ---------------------------------------------------------------
    panel.background = ggplot2::element_rect(
      # No Background Colour
      fill = plot_bg, colour = NA
    ),
    panel.border = ggplot2::element_rect(
      # No Background Colour
      colour = NA
    ),
    panel.spacing = grid::unit(8, "points"),
    
    ## Plot ----------------------------------------------------------------
    plot.background = ggplot2::element_rect(
      # No Background Colour
      fill = plot_bg, colour = NA
    ),
    plot.margin = ggplot2::margin(16, 16, 16, 16, unit = "pt")
    ) +
    ## Additional options passed by user ---------------------------------------
  theme(
    ...
  )

}
  
```







```{r mainpulate-data-basic}

plot_birds = bird_baths %>% 
  group_by(bird_type, urban_rural) %>% 
  summarise(count = sum(bird_count)) %>% 
  ungroup() %>% 
  filter(count > 100, !is.na(urban_rural)) %>%
  mutate(bird_type = fct_reorder(bird_type, count))

```



```{r plot-basic}

ggplot(plot_birds, aes(x = bird_type , y = count, fill = urban_rural )) +
  geom_col(position = "dodge", size = 3 ) +
  geom_text(aes(label = count), nudge_y = -14.0, color = "white") +
  coord_flip() + 
  labs(x = NULL, y = NULL, title = "Most seen Birds in Australia") +
  theme_allen() + 
  theme(legend.title = element_blank())



```



```{r}

plot_data =
  bird_baths %>%
  filter(complete.cases(.)) %>% ## Return a logical vector indicating which cases are complete, i.e., have no missing values.
  group_by(bird_type, urban_rural, survey_year) %>% 
  summarise(n = sum(bird_count)) %>%
  pivot_wider(names_from = urban_rural, values_from = n) %>%
  mutate(pct_urban = Urban/(Rural+Urban)) %>%
  filter(Urban > 0 & Rural > 0) %>%
  group_by(bird_type) %>%
  filter(n() == 2) %>%
  ungroup()


order_plot_data = plot_data %>% 
  mutate(survey_year = as.character(survey_year)) %>%
  select(-Rural, -Urban) %>%
  pivot_wider(names_from = survey_year, values_from = pct_urban) %>%
  mutate(delta = `2014`-`2015`)


city = order_plot_data %>%
  filter(delta < 0) %>%
  pull(bird_type)

camp = order_plot_data %>%
  filter(delta > 0) %>%
  pull(bird_type)




allow_list_bird_moving_to_city <-
  plot_data %>%
  filter(bird_type %in% city) %>%
  mutate(n = Rural + Urban) %>%
  group_by(bird_type) %>%
  summarise(total_n = sum(n)) %>%
  slice_max(total_n, n = 10, with_ties = FALSE) %>% # just taking the top 5 birds
  pull(bird_type) %>% unique()

allow_list_bird_moving_to_camp <-
  plot_data %>%
  filter(bird_type %in% camp) %>%
  mutate(n = Rural + Urban) %>%
  group_by(bird_type) %>%
  summarise(total_n = sum(n)) %>%
  slice_max(total_n, n = 10, with_ties = FALSE) %>%
  pull(bird_type) %>% unique()


my_order = order_plot_data %>%
  filter(
    bird_type %in% c(allow_list_bird_moving_to_city, allow_list_bird_moving_to_camp)) %>%
  arrange(delta) %>%
  pull(bird_type) %>% 
  unique()


 

  
  
  
  birds_clean = plot_data %>% 
    filter(bird_type %in% c(allow_list_bird_moving_to_city, allow_list_bird_moving_to_camp)) %>%
    mutate(survey_year = as.character(survey_year)) %>% 
    mutate(moving = if_else(bird_type %in% allow_list_bird_moving_to_city, 'Moving to city bird baths', 'Moving to camp bird baths')) %>% 
    mutate(moving = toupper(moving))
  

```


```{r}

ggplot(birds_clean, aes(x = factor(bird_type, levels = c(my_order)), y = pct_urban)) +
 geom_point(size = 4, aes(color = survey_year), alpha = .3) +
  geom_line(aes(group = bird_type), color = 'black', size = .5,
            arrow = arrow(length=unit(0.10,"cm"), ends="last", type = "closed")) +
  geom_hline(yintercept = 0.5, color = 'grey60') +
  geom_hline(yintercept = 0.5, color = 'grey60') +
  coord_flip() + 
  labs(x = NULL, y = "Percent Birds Moving", color = NULL) +
  facet_wrap(vars(moving), scales = 'free_y') +
  scale_y_continuous(limits = c(0,1), labels = scales::percent) +
  scale_color_manual(values = c("#feca00", "#d36328")) +
  theme_allen()
 





```




```{r}


alluvial_data = bird_baths %>%
  group_by(urban_rural, bioregions) %>%
  summarise(bird_count = sum(bird_count), .groups = "drop") %>%
  filter(!is.na(urban_rural), !is.na(bioregions)) 


  ggplot(alluvial_data, aes(axis1 = urban_rural, axis2 = bioregions, y = bird_count)) +
  geom_alluvium(aes(fill = urban_rural)) +
  geom_stratum(width = c(rep(1/10, 2), rep(1/2, 10)), position = "identity") +
  geom_text(stat = "stratum", aes(label = after_stat(stratum)), size = c(rep(4,2), rep(3,10))) +
  scale_x_discrete(expand = c(0,0), breaks = c(1,2), labels = c("Urban or rural location", "Region of Australia")) +
  labs(title = "Where have been reported more bird baths?", caption = "Data source: Cleary et al, 2016", x = NULL, y = NULL) +
  scale_fill_manual(values = c("#feca00", "#d36328")) +
  theme_void() +
  theme(legend.position = "none")
  
  
  
 
  
```




